#!/bin/bash

wallpapper=$(cd ~/Pictures/wallpapers/ ; ls | shuf | head -1)

echo $wallpapper ;

cd ~/Pictures/wallpapers/ && wal -i $wallpapper && cd $HOME && compileSuckless &&

#do this if dwm is in a while loop
ifloop=$(grep "dwm >/dev/null 2>&1" ~/.xinitrc 2>/dev/null || grep "dwm >/dev/null 2>&1" ~/.config/X11/xinitrc 2>/dev/null)
loop="  dwm >/dev/null 2>&1"
dwm=$(pidof dwm)
if [[ $ifloop = $loop && $dwm != '' ]]; then
  killall dwm || echo "THERE IS A ERROR WITH KILLING DWM"
elif [[ $dwm = '' ]]; then
  startx || echo "THERE IS A ERROR WITH STARTING XORG"
else
  echo "THERE IS A ERROR OR SOMETHING UNEXPECTED HAPPENDED"
fi

current=$(locate current-wallpapper.txt)
wallloc=$(locate $wallpapper | grep "wallpapers" | sed '/.cache/d' | sed 's/^$//g')
echo $wallloc > $current
